spring:
  application:
    name: justride-v2

spring.cloud.stream.bindings.violations-out.contentType: application/json
spring.cloud.stream.bindings.pods-in.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.pods-in.consumer.application-id: justride-v2
spring.cloud.stream.bindings.violations-out:
  destination: violations
spring.cloud.stream.bindings.pods-in:
  destination: pods


#Pod Events generator
spring.cloud.stream.bindings.violations.destination: violations
spring.cloud.stream.bindings.pods.destination: pods
spring.cloud.stream.bindings.violations.binder: kafka
spring.cloud.stream.bindings.pods.binder: kafka


